name: productservices
env:
  MAVEN: ./mvnw
on:
  push:
  pull_request:
    branches: [main]
    paths:
    - 'src/**'
    - 'pom.xml'
    - '.github/workflows/**'

jobs:
  
  build_test_release:
    runs-on: ubuntu-latest
    steps:
    - name: build and test
      run: |
        mvn clean install
    - name: "Build Docker image and push it to a Registry"
      run: |
        docker build -f Dockerfile -t sayan21/product-service .
        echo "push image"
        docker push sayan21/product-service:latest
